CREATE TABLE film
(
    id          BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(255)    NOT NULL,
    release_year        INT,
    country     VARCHAR(100),
    genres      VARCHAR(100)[]  NOT NULL    DEFAULT '{}',
    description TEXT,
    poster_url  VARCHAR(1000),
    created_ts  TIMESTAMP       NOT NULL    DEFAULT CURRENT_TIMESTAMP,
    updated_ts  TIMESTAMP       NOT NULL    DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE actor
(
    id          BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100)    NOT NULL,
    created_ts  TIMESTAMP       NOT NULL    DEFAULT CURRENT_TIMESTAMP,
    updated_ts  TIMESTAMP       NOT NULL    DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE director
(
    id          BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100)    NOT NULL,
    created_ts  TIMESTAMP       NOT NULL    DEFAULT CURRENT_TIMESTAMP,
    updated_ts  TIMESTAMP       NOT NULL    DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE film_actor
(
    film_id     BIGINT          NOT NULL,
    actor_id    BIGINT          NOT NULL,
    PRIMARY KEY (film_id, actor_id),
    CONSTRAINT film_actor_film_fk       FOREIGN KEY (film_id)   REFERENCES film(id),
    CONSTRAINT film_actor_actor_fk      FOREIGN KEY (actor_id)  REFERENCES actor(id)
);

CREATE TABLE film_director
(
    film_id     BIGINT          NOT NULL,
    director_id BIGINT          NOT NULL,
    PRIMARY KEY (film_id, director_id),
    CONSTRAINT film_director_film_fk        FOREIGN KEY (film_id)       REFERENCES film(id),
    CONSTRAINT film_director_director_fk    FOREIGN KEY (director_id)   REFERENCES director(id)
)
